# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 277b5a4c443dc2a589b958824c782431aced111a861e1d2d3d520141468b58f090c5fa7beed1b1c18ce0c3b77e7eb8c015364fdbda12bb19c729021a4715d776

test:
  secret_key_base: 587e2d7fe7b7c6804e031ae114bfa32b7a708027088e69f7608bf1cceafe6d2473e8cd5cf6d208a02f415b39496a5fa9dc9148cab52357f672c7ee56c5f59ac7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
